basic/basic/urls.py
from django.contrib import admin
from django.urls import path,include
from basicapp import views

urlpatterns = [
    path('',views.index,name='index'),
    path("admin/", admin.site.urls),
    path('basicapp/',include('basicapp.urls')),
    path('logout/',views.user_logout,name='logout')


]

basic/basicapp/urls.py
from django.urls import path
from basicapp import views

app_name='basicapp'

urlpatterns=[
    path('Registration/',views.Registration,name='Registration'),
    path('login/',views.user_login,name='user_login')

]

basic/basicapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfileInfo(models.Model):

    user=models.OneToOneField(User,on_delete=models.CASCADE)

    portfolio_site=models.URLField(blank=True)
    profile_pic=models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

basic/forms.py
from django import forms
from django.contrib.auth.models import User
from basicapp.models import UserProfileInfo


class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput)


    class Meta():
        model=User
        fields=['username','email','password']

class UserProfileForm(forms.ModelForm):
    class Meta():
        model=UserProfileInfo
        fields=['portfolio_site','profile_pic']

basic/basicapp/views.py
from django.shortcuts import render
from forms import UserForm,UserProfileForm 

from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect,HttpResponse
from django.contrib.auth import authenticate,login,logout
from django.contrib import messages



# Create your views here.
def index(request):
    return render(request,'basicapp/index.html')


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))



def Registration(request):

    registered=False
    user_form=UserForm()
    profile_form=UserProfileForm()

    if request.method=='POST':
        user_form=UserForm(request.POST)
        profile_form=UserProfileForm(request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user=user_form.save()
            user.set_password(user.password)
            user.save()

            profile=profile_form.save(commit=False)
            profile.user=user

            if 'profile_pic' in request.FILES:
                profile.profile_pic=request.FILES['profile_pic']
            profile.save()
            registered=True

        else:
            print(user_form.errors,profile_form.errors)

    else:
        user_form=UserForm()
        profile_form=UserProfileForm()

    return render(request ,'basicapp/Registration.html',{'user_form':user_form,
                                                         'profile_form':profile_form,
                                                         'registered':registered})
def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                messages.error(request, "Invalid username or password.")
        else:
            messages.error(request, "Invalid username or password.")
    else:
        user = authenticate()
        return render(request, "basicapp/login.html")

basic/templates/basicapp/Registration.html
{% extends 'basicapp/base.html' %}
    {%block content%}
    <div class="jumbotron">
        {% if registered %}
            <h1>Thank You For the Registration</h1>
        {% else %}
            <h1>Welcome to the RegisterForm</h1>

            <h2>Register Here</h2>
            <form method="POST" enctype="multipart/form-data">
                {{user_form.as_p}}
                {% csrf_token %}
                {{profile_form.as_p}}
                <input type="submit" class="btn btn-primary" value="Register">
            </form>
        {%endif%}
    </div>
    {%endblock%}

basic/templates/basicapp/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="navbar-nav">
        {# Django Home Link / Admin Link / Register Link#}
        <a class="navbar-brand" href="{% url 'index' %}">DJANGO</a>
        <a class="nav-item nav-link" href="{% url 'admin:index' %}">Admin</a>
        <a class="nav-item nav-link" href="{% url 'basicapp:Registration' %}">Register</a>

        {# Some logic on what to display for last item#}
        {% if user.is_authenticated %}
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
        {% else %}
          <a class="nav-link" href="{% url 'basicapp:user_login' %}">Login</a>
        {% endif %}
      </div>
    </nav>

    <div class="container">
    {% block content %}
    {% endblock %}
    </div>


  </body>
</html>

basic/templates/basicapp/index.html
{% extends 'basicapp/base.html' %}
    {%block content%}
        <div class="jumbotron">
            <h1>Welcome to index.html</h1>
        </div>
    {%endblock%}

basic/templates/basicapp/login.html
{% extends 'basicapp/base.html' %}
    {%block content%}
    <div class="jumbotron">
        <h1>please login here</h1>
        <form method="post" action="{% url 'basicapp:user_login' %}">

            {% csrf_token %}
            <label for="username">Username:</label>
            <input type="text" name="username" placeholder="Enter your name">
            <label for="password">Password:</label>
            <input type="password" name="password" placeholder="Enter password">

            <input type="submit" class="btn btn-primary" value="Login">
        </form>
    </div>
    {%endblock%}